language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install: "pip install -r requirements.txt"

# install nfcu
before_install:
  - pip install -e .

# command to run tests
script: pytest test/nfcu.py

# code coverage
after_success:
  - coveralls
