language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

before_install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install -e .

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: "pylint"
      script: pipenv run pylint nfcu/
    - name: "pycodestyle"
      script: pipenv run pycodestyle nfcu/
    - stage: test
      name: "pytest"
      script: pipenv run pytest test/

after_success:
  - pipenv run coveralls
